# coding: utf-8

"""
    mVisa API

    mVisa is a simple, secure and fast way to pay and be paid using mobile phones. mVisa enables a range of payment use cases and is technology agnostic-leveraging evolving POS environment such as QR codes and works on both smart or feature phones.

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PurchaseIdentifier(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, type=None, reference_number=None):
        """
        PurchaseIdentifier - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'type': 'str',
            'reference_number': 'str'
        }

        self.attribute_map = {
            'type': 'type',
            'reference_number': 'referenceNumber'
        }

        self._type = type
        self._reference_number = reference_number

    @property
    def type(self):
        """
        Gets the type of this PurchaseIdentifier.
        Populate <b>0</b>

        :return: The type of this PurchaseIdentifier.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this PurchaseIdentifier.
        Populate <b>0</b>

        :param type: The type of this PurchaseIdentifier.
        :type: str
        """

        self._type = type

    @property
    def reference_number(self):
        """
        Gets the reference_number of this PurchaseIdentifier.
        Populate this field with the Additional Data - Value 1 as defined in merchant data specification with reference to EMVCo QR specification (Merchant-Presented Mode).<br>Below is an example of Additional Data Field Template '62' having a value of '62150103XYZ05049999'<br><table border=1><tr><td width='20%'>ID</td><td width='20%'>Descripton</td><td width='20%'>Value</td><td width='40%'>Comments</td></tr><tr><td>'62'-'01'</td><td>Bill Number</td><td>XYZ</td><td>Additional Data - Value 1</td></tr><tr><td>'62'-'05'</td><td>Reference Label</td><td>9999</td><td>Additional Data - Value 2</td></tr></table>

        :return: The reference_number of this PurchaseIdentifier.
        :rtype: str
        """
        return self._reference_number

    @reference_number.setter
    def reference_number(self, reference_number):
        """
        Sets the reference_number of this PurchaseIdentifier.
        Populate this field with the Additional Data - Value 1 as defined in merchant data specification with reference to EMVCo QR specification (Merchant-Presented Mode).<br>Below is an example of Additional Data Field Template '62' having a value of '62150103XYZ05049999'<br><table border=1><tr><td width='20%'>ID</td><td width='20%'>Descripton</td><td width='20%'>Value</td><td width='40%'>Comments</td></tr><tr><td>'62'-'01'</td><td>Bill Number</td><td>XYZ</td><td>Additional Data - Value 1</td></tr><tr><td>'62'-'05'</td><td>Reference Label</td><td>9999</td><td>Additional Data - Value 2</td></tr></table>

        :param reference_number: The reference_number of this PurchaseIdentifier.
        :type: str
        """

        self._reference_number = reference_number

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PurchaseIdentifier):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------