# coding: utf-8

"""
    Queue Insights API

    Visa Queue Insights - Deliver Predicted Waiting Time for select merchants to our clients through the Visa Developer Platform

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.feedback_list import FeedbackList
from .models.feedback_list_inner import FeedbackListInner
from .models.feedback_update_list import FeedbackUpdateList
from .models.feedback_update_list_inner import FeedbackUpdateListInner
from .models.merchant_list import MerchantList
from .models.merchant_list_inner import MerchantListInner
from .models.request_data import RequestData
from .models.request_header import RequestHeader
from .models.response_data import ResponseData
from .models.response_header import ResponseHeader
from .models.status import Status
from .models.vqi_servicepost_payload import VqiServicepostPayload
from .models.vqi_servicepost_response import VqiServicepostResponse

# import apis into sdk package
from .apis.vqi_api import VqiApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()

# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------