# coding: utf-8

"""
    Adjustment API

    The AdjustReverseFundsTransactions resource credits (pushes back) funds to the sender&apos;s Visa account by initiating a financial message called an Account Funding Transaction Reversal (AFTR) without the 24 hours limitation in the AFTR.

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AdjustreversefundspostResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, date_and_time_transmission=None, transaction_identifier=None, action_code=None):
        """
        AdjustreversefundspostResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'date_and_time_transmission': 'str',
            'transaction_identifier': 'int',
            'action_code': 'str'
        }

        self.attribute_map = {
            'date_and_time_transmission': 'dateAndTimeTransmission',
            'transaction_identifier': 'transactionIdentifier',
            'action_code': 'actionCode'
        }

        self._date_and_time_transmission = date_and_time_transmission
        self._transaction_identifier = transaction_identifier
        self._action_code = action_code

    @property
    def date_and_time_transmission(self):
        """
        Gets the date_and_time_transmission of this AdjustreversefundspostResponse.
        This field contains the year, month, day, and time the transaction was processed by Visa Direct. Example: 2016-01-15T07:03:52.000Z

        :return: The date_and_time_transmission of this AdjustreversefundspostResponse.
        :rtype: str
        """
        return self._date_and_time_transmission

    @date_and_time_transmission.setter
    def date_and_time_transmission(self, date_and_time_transmission):
        """
        Sets the date_and_time_transmission of this AdjustreversefundspostResponse.
        This field contains the year, month, day, and time the transaction was processed by Visa Direct. Example: 2016-01-15T07:03:52.000Z

        :param date_and_time_transmission: The date_and_time_transmission of this AdjustreversefundspostResponse.
        :type: str
        """
        if date_and_time_transmission is None:
            raise ValueError("Invalid value for `date_and_time_transmission`, must not be `None`")

        self._date_and_time_transmission = date_and_time_transmission

    @property
    def transaction_identifier(self):
        """
        Gets the transaction_identifier of this AdjustreversefundspostResponse.
        Visa transaction identifier .

        :return: The transaction_identifier of this AdjustreversefundspostResponse.
        :rtype: int
        """
        return self._transaction_identifier

    @transaction_identifier.setter
    def transaction_identifier(self, transaction_identifier):
        """
        Sets the transaction_identifier of this AdjustreversefundspostResponse.
        Visa transaction identifier .

        :param transaction_identifier: The transaction_identifier of this AdjustreversefundspostResponse.
        :type: int
        """
        if transaction_identifier is None:
            raise ValueError("Invalid value for `transaction_identifier`, must not be `None`")

        self._transaction_identifier = transaction_identifier

    @property
    def action_code(self):
        """
        Gets the action_code of this AdjustreversefundspostResponse.
        The results of the transaction request

        :return: The action_code of this AdjustreversefundspostResponse.
        :rtype: str
        """
        return self._action_code

    @action_code.setter
    def action_code(self, action_code):
        """
        Sets the action_code of this AdjustreversefundspostResponse.
        The results of the transaction request

        :param action_code: The action_code of this AdjustreversefundspostResponse.
        :type: str
        """
        if action_code is None:
            raise ValueError("Invalid value for `action_code`, must not be `None`")

        self._action_code = action_code

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AdjustreversefundspostResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------