# coding: utf-8

"""
    Mobile Push Payment Refund API

    Mobile Push Payment is a simple, secure and fast way to pay and be paid using mobile phones. Mobile Push Payment enables a range of payment use cases and is technology agnostic-leveraging evolving POS environment such as QR codes and works on both smart or feature phones.

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class MerchandiseReturnPostpostPayload(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, local_transaction_date_time=None, recipient_primary_account_number=None, merchant_category_code=None, fee_program_indicator=None, transaction_fee_amt=None, retrieval_reference_number=None, acquirer_country_code=None, amount=None, card_acceptor=None, acquiring_bin=None, systems_trace_audit_number=None, transaction_currency_code=None, merchant_verification_value=None, card_expiry_date=None, transaction_identifier=None):
        """
        MerchandiseReturnPostpostPayload - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'local_transaction_date_time': 'str',
            'recipient_primary_account_number': 'str',
            'merchant_category_code': 'str',
            'fee_program_indicator': 'str',
            'transaction_fee_amt': 'str',
            'retrieval_reference_number': 'str',
            'acquirer_country_code': 'str',
            'amount': 'str',
            'card_acceptor': 'CardAcceptor',
            'acquiring_bin': 'str',
            'systems_trace_audit_number': 'str',
            'transaction_currency_code': 'str',
            'merchant_verification_value': 'MerchantVerificationValue',
            'card_expiry_date': 'str',
            'transaction_identifier': 'str'
        }

        self.attribute_map = {
            'local_transaction_date_time': 'localTransactionDateTime',
            'recipient_primary_account_number': 'recipientPrimaryAccountNumber',
            'merchant_category_code': 'merchantCategoryCode',
            'fee_program_indicator': 'feeProgramIndicator',
            'transaction_fee_amt': 'transactionFeeAmt',
            'retrieval_reference_number': 'retrievalReferenceNumber',
            'acquirer_country_code': 'acquirerCountryCode',
            'amount': 'amount',
            'card_acceptor': 'cardAcceptor',
            'acquiring_bin': 'acquiringBin',
            'systems_trace_audit_number': 'systemsTraceAuditNumber',
            'transaction_currency_code': 'transactionCurrencyCode',
            'merchant_verification_value': 'merchantVerificationValue',
            'card_expiry_date': 'cardExpiryDate',
            'transaction_identifier': 'transactionIdentifier'
        }

        self._local_transaction_date_time = local_transaction_date_time
        self._recipient_primary_account_number = recipient_primary_account_number
        self._merchant_category_code = merchant_category_code
        self._fee_program_indicator = fee_program_indicator
        self._transaction_fee_amt = transaction_fee_amt
        self._retrieval_reference_number = retrieval_reference_number
        self._acquirer_country_code = acquirer_country_code
        self._amount = amount
        self._card_acceptor = card_acceptor
        self._acquiring_bin = acquiring_bin
        self._systems_trace_audit_number = systems_trace_audit_number
        self._transaction_currency_code = transaction_currency_code
        self._merchant_verification_value = merchant_verification_value
        self._card_expiry_date = card_expiry_date
        self._transaction_identifier = transaction_identifier

    @property
    def local_transaction_date_time(self):
        """
        Gets the local_transaction_date_time of this MerchandiseReturnPostpostPayload.
        This should be +/- 3 days from the current date.The date is in yyyy-mm-ddThh:mm:ss format.

        :return: The local_transaction_date_time of this MerchandiseReturnPostpostPayload.
        :rtype: str
        """
        return self._local_transaction_date_time

    @local_transaction_date_time.setter
    def local_transaction_date_time(self, local_transaction_date_time):
        """
        Sets the local_transaction_date_time of this MerchandiseReturnPostpostPayload.
        This should be +/- 3 days from the current date.The date is in yyyy-mm-ddThh:mm:ss format.

        :param local_transaction_date_time: The local_transaction_date_time of this MerchandiseReturnPostpostPayload.
        :type: str
        """
        if local_transaction_date_time is None:
            raise ValueError("Invalid value for `local_transaction_date_time`, must not be `None`")

        self._local_transaction_date_time = local_transaction_date_time

    @property
    def recipient_primary_account_number(self):
        """
        Gets the recipient_primary_account_number of this MerchandiseReturnPostpostPayload.
        Populate with Consumer PAN. This is the same PAN the consumer used in merchant payment.

        :return: The recipient_primary_account_number of this MerchandiseReturnPostpostPayload.
        :rtype: str
        """
        return self._recipient_primary_account_number

    @recipient_primary_account_number.setter
    def recipient_primary_account_number(self, recipient_primary_account_number):
        """
        Sets the recipient_primary_account_number of this MerchandiseReturnPostpostPayload.
        Populate with Consumer PAN. This is the same PAN the consumer used in merchant payment.

        :param recipient_primary_account_number: The recipient_primary_account_number of this MerchandiseReturnPostpostPayload.
        :type: str
        """
        if recipient_primary_account_number is None:
            raise ValueError("Invalid value for `recipient_primary_account_number`, must not be `None`")

        self._recipient_primary_account_number = recipient_primary_account_number

    @property
    def merchant_category_code(self):
        """
        Gets the merchant_category_code of this MerchandiseReturnPostpostPayload.
        This is to be populated with the MCC of the merchant initiating the refund.

        :return: The merchant_category_code of this MerchandiseReturnPostpostPayload.
        :rtype: str
        """
        return self._merchant_category_code

    @merchant_category_code.setter
    def merchant_category_code(self, merchant_category_code):
        """
        Sets the merchant_category_code of this MerchandiseReturnPostpostPayload.
        This is to be populated with the MCC of the merchant initiating the refund.

        :param merchant_category_code: The merchant_category_code of this MerchandiseReturnPostpostPayload.
        :type: str
        """
        if merchant_category_code is None:
            raise ValueError("Invalid value for `merchant_category_code`, must not be `None`")

        self._merchant_category_code = merchant_category_code

    @property
    def fee_program_indicator(self):
        """
        Gets the fee_program_indicator of this MerchandiseReturnPostpostPayload.
        Originators can leave this field blank.

        :return: The fee_program_indicator of this MerchandiseReturnPostpostPayload.
        :rtype: str
        """
        return self._fee_program_indicator

    @fee_program_indicator.setter
    def fee_program_indicator(self, fee_program_indicator):
        """
        Sets the fee_program_indicator of this MerchandiseReturnPostpostPayload.
        Originators can leave this field blank.

        :param fee_program_indicator: The fee_program_indicator of this MerchandiseReturnPostpostPayload.
        :type: str
        """

        self._fee_program_indicator = fee_program_indicator

    @property
    def transaction_fee_amt(self):
        """
        Gets the transaction_fee_amt of this MerchandiseReturnPostpostPayload.
        Prefix ‘C’ Originators are required to populate convenience fee amount in this field to be returned, if presented in the original message

        :return: The transaction_fee_amt of this MerchandiseReturnPostpostPayload.
        :rtype: str
        """
        return self._transaction_fee_amt

    @transaction_fee_amt.setter
    def transaction_fee_amt(self, transaction_fee_amt):
        """
        Sets the transaction_fee_amt of this MerchandiseReturnPostpostPayload.
        Prefix ‘C’ Originators are required to populate convenience fee amount in this field to be returned, if presented in the original message

        :param transaction_fee_amt: The transaction_fee_amt of this MerchandiseReturnPostpostPayload.
        :type: str
        """

        self._transaction_fee_amt = transaction_fee_amt

    @property
    def retrieval_reference_number(self):
        """
        Gets the retrieval_reference_number of this MerchandiseReturnPostpostPayload.
        Numeric only. This is a key data element for matching a message to others within a given transaction set.Recommended Format : ydddhhnnnnnnThe first fours digits must be a valid yddd date in the Julian date format, where the first digit = 0-9 (last digit of current year) and the next three digits = 001-366 (number of the day in the year). hh can be the two digit hour in a 24 hour clock (00-23) during which the transaction is performed.<br><br> nnnnnn can be the SystemsTraceAuditNumber or any 6 digit number.

        :return: The retrieval_reference_number of this MerchandiseReturnPostpostPayload.
        :rtype: str
        """
        return self._retrieval_reference_number

    @retrieval_reference_number.setter
    def retrieval_reference_number(self, retrieval_reference_number):
        """
        Sets the retrieval_reference_number of this MerchandiseReturnPostpostPayload.
        Numeric only. This is a key data element for matching a message to others within a given transaction set.Recommended Format : ydddhhnnnnnnThe first fours digits must be a valid yddd date in the Julian date format, where the first digit = 0-9 (last digit of current year) and the next three digits = 001-366 (number of the day in the year). hh can be the two digit hour in a 24 hour clock (00-23) during which the transaction is performed.<br><br> nnnnnn can be the SystemsTraceAuditNumber or any 6 digit number.

        :param retrieval_reference_number: The retrieval_reference_number of this MerchandiseReturnPostpostPayload.
        :type: str
        """
        if retrieval_reference_number is None:
            raise ValueError("Invalid value for `retrieval_reference_number`, must not be `None`")

        self._retrieval_reference_number = retrieval_reference_number

    @property
    def acquirer_country_code(self):
        """
        Gets the acquirer_country_code of this MerchandiseReturnPostpostPayload.
        Use a 3-digit numeric country code for the country. This must match the information provided during program enrollment.

        :return: The acquirer_country_code of this MerchandiseReturnPostpostPayload.
        :rtype: str
        """
        return self._acquirer_country_code

    @acquirer_country_code.setter
    def acquirer_country_code(self, acquirer_country_code):
        """
        Sets the acquirer_country_code of this MerchandiseReturnPostpostPayload.
        Use a 3-digit numeric country code for the country. This must match the information provided during program enrollment.

        :param acquirer_country_code: The acquirer_country_code of this MerchandiseReturnPostpostPayload.
        :type: str
        """
        if acquirer_country_code is None:
            raise ValueError("Invalid value for `acquirer_country_code`, must not be `None`")

        self._acquirer_country_code = acquirer_country_code

    @property
    def amount(self):
        """
        Gets the amount of this MerchandiseReturnPostpostPayload.
        Refunded amount in original transaction currency.

        :return: The amount of this MerchandiseReturnPostpostPayload.
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """
        Sets the amount of this MerchandiseReturnPostpostPayload.
        Refunded amount in original transaction currency.

        :param amount: The amount of this MerchandiseReturnPostpostPayload.
        :type: str
        """
        if amount is None:
            raise ValueError("Invalid value for `amount`, must not be `None`")

        self._amount = amount

    @property
    def card_acceptor(self):
        """
        Gets the card_acceptor of this MerchandiseReturnPostpostPayload.

        :return: The card_acceptor of this MerchandiseReturnPostpostPayload.
        :rtype: CardAcceptor
        """
        return self._card_acceptor

    @card_acceptor.setter
    def card_acceptor(self, card_acceptor):
        """
        Sets the card_acceptor of this MerchandiseReturnPostpostPayload.

        :param card_acceptor: The card_acceptor of this MerchandiseReturnPostpostPayload.
        :type: CardAcceptor
        """
        if card_acceptor is None:
            raise ValueError("Invalid value for `card_acceptor`, must not be `None`")

        self._card_acceptor = card_acceptor

    @property
    def acquiring_bin(self):
        """
        Gets the acquiring_bin of this MerchandiseReturnPostpostPayload.
        This BIN number identifies the originator of refund transaction. This must match the information provided during enrollment.

        :return: The acquiring_bin of this MerchandiseReturnPostpostPayload.
        :rtype: str
        """
        return self._acquiring_bin

    @acquiring_bin.setter
    def acquiring_bin(self, acquiring_bin):
        """
        Sets the acquiring_bin of this MerchandiseReturnPostpostPayload.
        This BIN number identifies the originator of refund transaction. This must match the information provided during enrollment.

        :param acquiring_bin: The acquiring_bin of this MerchandiseReturnPostpostPayload.
        :type: str
        """
        if acquiring_bin is None:
            raise ValueError("Invalid value for `acquiring_bin`, must not be `None`")

        self._acquiring_bin = acquiring_bin

    @property
    def systems_trace_audit_number(self):
        """
        Gets the systems_trace_audit_number of this MerchandiseReturnPostpostPayload.
        Numeric only. This must be the same value as in the original request.

        :return: The systems_trace_audit_number of this MerchandiseReturnPostpostPayload.
        :rtype: str
        """
        return self._systems_trace_audit_number

    @systems_trace_audit_number.setter
    def systems_trace_audit_number(self, systems_trace_audit_number):
        """
        Sets the systems_trace_audit_number of this MerchandiseReturnPostpostPayload.
        Numeric only. This must be the same value as in the original request.

        :param systems_trace_audit_number: The systems_trace_audit_number of this MerchandiseReturnPostpostPayload.
        :type: str
        """
        if systems_trace_audit_number is None:
            raise ValueError("Invalid value for `systems_trace_audit_number`, must not be `None`")

        self._systems_trace_audit_number = systems_trace_audit_number

    @property
    def transaction_currency_code(self):
        """
        Gets the transaction_currency_code of this MerchandiseReturnPostpostPayload.
        The code in this field must always reflect the currency associated to the amount

        :return: The transaction_currency_code of this MerchandiseReturnPostpostPayload.
        :rtype: str
        """
        return self._transaction_currency_code

    @transaction_currency_code.setter
    def transaction_currency_code(self, transaction_currency_code):
        """
        Sets the transaction_currency_code of this MerchandiseReturnPostpostPayload.
        The code in this field must always reflect the currency associated to the amount

        :param transaction_currency_code: The transaction_currency_code of this MerchandiseReturnPostpostPayload.
        :type: str
        """
        if transaction_currency_code is None:
            raise ValueError("Invalid value for `transaction_currency_code`, must not be `None`")

        self._transaction_currency_code = transaction_currency_code

    @property
    def merchant_verification_value(self):
        """
        Gets the merchant_verification_value of this MerchandiseReturnPostpostPayload.

        :return: The merchant_verification_value of this MerchandiseReturnPostpostPayload.
        :rtype: MerchantVerificationValue
        """
        return self._merchant_verification_value

    @merchant_verification_value.setter
    def merchant_verification_value(self, merchant_verification_value):
        """
        Sets the merchant_verification_value of this MerchandiseReturnPostpostPayload.

        :param merchant_verification_value: The merchant_verification_value of this MerchandiseReturnPostpostPayload.
        :type: MerchantVerificationValue
        """

        self._merchant_verification_value = merchant_verification_value

    @property
    def card_expiry_date(self):
        """
        Gets the card_expiry_date of this MerchandiseReturnPostpostPayload.
        The expiration date for the Consumer PAN in recipientPrimaryAccountNumber

        :return: The card_expiry_date of this MerchandiseReturnPostpostPayload.
        :rtype: str
        """
        return self._card_expiry_date

    @card_expiry_date.setter
    def card_expiry_date(self, card_expiry_date):
        """
        Sets the card_expiry_date of this MerchandiseReturnPostpostPayload.
        The expiration date for the Consumer PAN in recipientPrimaryAccountNumber

        :param card_expiry_date: The card_expiry_date of this MerchandiseReturnPostpostPayload.
        :type: str
        """

        self._card_expiry_date = card_expiry_date

    @property
    def transaction_identifier(self):
        """
        Gets the transaction_identifier of this MerchandiseReturnPostpostPayload.
        <b>Conditional.</b> If originator submits merchant payment transaction using MerchantPushPayments API, they should submit the same value of transactionIdentifier in API request. Otherwise, do not use this field in the API request.

        :return: The transaction_identifier of this MerchandiseReturnPostpostPayload.
        :rtype: str
        """
        return self._transaction_identifier

    @transaction_identifier.setter
    def transaction_identifier(self, transaction_identifier):
        """
        Sets the transaction_identifier of this MerchandiseReturnPostpostPayload.
        <b>Conditional.</b> If originator submits merchant payment transaction using MerchantPushPayments API, they should submit the same value of transactionIdentifier in API request. Otherwise, do not use this field in the API request.

        :param transaction_identifier: The transaction_identifier of this MerchandiseReturnPostpostPayload.
        :type: str
        """

        self._transaction_identifier = transaction_identifier

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, MerchandiseReturnPostpostPayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------