# coding: utf-8

"""
    Queue Insights API

    Visa Queue Insights - Deliver Predicted Waiting Time for select merchants to our clients through the Visa Developer Platform

    OpenAPI spec version: v1
    Contact: 
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class MerchantListInner(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, city=None, name=None, zip=None, country=None, wait_time=None, state=None, feedback_correlation_id=None):
        """
        MerchantListInner - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'city': 'str',
            'name': 'str',
            'zip': 'str',
            'country': 'str',
            'wait_time': 'str',
            'state': 'str',
            'feedback_correlation_id': 'str'
        }

        self.attribute_map = {
            'city': 'city',
            'name': 'name',
            'zip': 'zip',
            'country': 'country',
            'wait_time': 'waitTime',
            'state': 'state',
            'feedback_correlation_id': 'feedbackCorrelationID'
        }

        self._city = city
        self._name = name
        self._zip = zip
        self._country = country
        self._wait_time = wait_time
        self._state = state
        self._feedback_correlation_id = feedback_correlation_id

    @property
    def city(self):
        """
        Gets the city of this MerchantListInner.
        city of the associated merchant

        :return: The city of this MerchantListInner.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city):
        """
        Sets the city of this MerchantListInner.
        city of the associated merchant

        :param city: The city of this MerchantListInner.
        :type: str
        """

        self._city = city

    @property
    def name(self):
        """
        Gets the name of this MerchantListInner.
        Name of the merchant for which prediction has been made

        :return: The name of this MerchantListInner.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this MerchantListInner.
        Name of the merchant for which prediction has been made

        :param name: The name of this MerchantListInner.
        :type: str
        """

        self._name = name

    @property
    def zip(self):
        """
        Gets the zip of this MerchantListInner.
        zip of the associated merchant

        :return: The zip of this MerchantListInner.
        :rtype: str
        """
        return self._zip

    @zip.setter
    def zip(self, zip):
        """
        Sets the zip of this MerchantListInner.
        zip of the associated merchant

        :param zip: The zip of this MerchantListInner.
        :type: str
        """

        self._zip = zip

    @property
    def country(self):
        """
        Gets the country of this MerchantListInner.
        country of the associated merchant

        :return: The country of this MerchantListInner.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """
        Sets the country of this MerchantListInner.
        country of the associated merchant

        :param country: The country of this MerchantListInner.
        :type: str
        """

        self._country = country

    @property
    def wait_time(self):
        """
        Gets the wait_time of this MerchantListInner.
        Predicted waitTime of the associated merchant

        :return: The wait_time of this MerchantListInner.
        :rtype: str
        """
        return self._wait_time

    @wait_time.setter
    def wait_time(self, wait_time):
        """
        Sets the wait_time of this MerchantListInner.
        Predicted waitTime of the associated merchant

        :param wait_time: The wait_time of this MerchantListInner.
        :type: str
        """

        self._wait_time = wait_time

    @property
    def state(self):
        """
        Gets the state of this MerchantListInner.
        state of the associated merchant

        :return: The state of this MerchantListInner.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """
        Sets the state of this MerchantListInner.
        state of the associated merchant

        :param state: The state of this MerchantListInner.
        :type: str
        """

        self._state = state

    @property
    def feedback_correlation_id(self):
        """
        Gets the feedback_correlation_id of this MerchantListInner.
        feedbackCorrelationID of the associated merchant, the user uses this id to provide feedback to us- UUID Java Format

        :return: The feedback_correlation_id of this MerchantListInner.
        :rtype: str
        """
        return self._feedback_correlation_id

    @feedback_correlation_id.setter
    def feedback_correlation_id(self, feedback_correlation_id):
        """
        Sets the feedback_correlation_id of this MerchantListInner.
        feedbackCorrelationID of the associated merchant, the user uses this id to provide feedback to us- UUID Java Format

        :param feedback_correlation_id: The feedback_correlation_id of this MerchantListInner.
        :type: str
        """

        self._feedback_correlation_id = feedback_correlation_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, MerchantListInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other

# ----------------------------------------------------------------------------------------------------------------------
# © Copyright 2018 Visa. All Rights Reserved.
#
# NOTICE: The software and accompanying information and documentation (together, the “Software”) remain the property of
# and are proprietary to Visa and its suppliers and affiliates. The Software remains protected by intellectual property
# rights and may be covered by U.S. and foreign patents or patent applications. The Software is licensed and not sold.
#
# By accessing the Software you are agreeing to Visa's terms of use (developer.visa.com/terms) and privacy policy
# (developer.visa.com/privacy). In addition, all permissible uses of the Software must be in support of Visa products,
# programs and services provided through the Visa Developer Program (VDP) platform only (developer.visa.com).
# THE SOFTWARE AND ANY ASSOCIATED INFORMATION OR DOCUMENTATION IS PROVIDED ON AN “AS IS,” “AS AVAILABLE,” “WITH ALL
# FAULTS” BASIS WITHOUT WARRANTY OR CONDITION OF ANY KIND. YOUR USE IS AT YOUR OWN RISK.
# ----------------------------------------------------------------------------------------------------------------------